services:
  # Service pour l'application Next.js en mode développement
  app-dev:
    build:
      context: ..  # Le contexte est le dossier parent (FAC-DASHBOARD)
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:root@db:5432/factura
    depends_on:
      - db
    volumes:
      - ..:/app  # Monter le dossier parent dans /app
    entrypoint: ["yarn", "run", "dev"]  # Lancer en mode développement

  # Service pour PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: factura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: