import type { Metadata } from "next";

import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import themeSystem from "@/config/themes";
import { AuthProvider } from "./components/AuthProvider";
import { getServerAuthSession } from "@/server/auth";

import QueryProvider from "./components/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();

  return (
    <html lang="fr" suppressHydrationWarning={true}>
      <body>
        <QueryProvider>
          <ChakraProvider value={themeSystem}>
            <AuthProvider session={session}>{children}</AuthProvider>
          </ChakraProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
