name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      pull-requests: write 
    strategy:
        matrix:
          node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
